data:
  path: "C:/Users/alimcinella/.cache/kagglehub/datasets/samuelcortinhas/muffin-vs-chihuahua-image-classification/versions/2"
  dataset_name: "samuelcortinhas/muffin-vs-chihuahua-image-classification"